### ISSUE TITLE
Copy binary endian

### ISSUE THREAD

**Issue by Malllm** [hannesmuehleisen/MonetDBLite-Java#2]
When using a sql call through JDBC like:
copy binary into ${table} from (${file1}, ${file2})
It appears that MonetDBLite-Java expects the files the be in big endian while ordinary monetDB expects them to be in little endian. I'm not sure which one would be the correct one to use but it does seems very odd that they differ.
This is on a 64-bit Windows 7 if that makes any difference.

**Comment by PedroTadim** [comment]
The [JVM is always Big Endian](https://stackoverflow.com/questions/981549/javas-virtual-machines-endianness?lq=1), on any architecture, so that's why the files must be Big Endian. Meanwhile an ordinary MonetDB server, which runs natively, expects the files to be in the endianess of the underlying architecture, thus will vary from machine. [x86_64 is Little Endian](https://stackoverflow.com/questions/6018386/so-on-x86-64-its-big-endian?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). I have a test for the copy binary into command [here](https://github.com/hannesmuehleisen/MonetDBLite-Java/blob/master/monetdb-java-lite/src/test/java/nl/cwi/monetdb/tests/RegularAPITests.java#L928). I think there is no way around for this.

**Comment by PedroTadim** [comment]
But I can check at runtime the CPU endianess and do the swap.

**Comment by Malllm** [comment]
Hmm, what you're saying seem to hold true for integers but following some further testing I found that doubles seems to stick to native endianess (i.e. little endian in this case).

**Comment by PedroTadim** [comment]
Yes, I forgot to check some types. I already fixed and it will be available in the next release.

**Comment by Malllm** [comment]
Alright, sounds like it is taken care of then :)
